# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YO7S3IQkf+m4NFg6cj+oX9wljXqrDbdtvvYvfha69nuSxKVZrN4GRkq1+rDx0VVun0iO0jaO85bOfnCAMt2ZYOZx+A753uTUfy6XpA7jnIOozk3d2hIiALN40unxfxuV/DUJSgJtPqe4z+UHhfBo+JzqpmAnK3w7i2B4qPAd3BNgN2oEDOCi+dwMqHey1rOEqW/nhG1hz0PBUWGqhoG/J0YAMO9KGWIS3ocTzFddPH8NeEYqQ4+37jM8SM8q1FH0h3M5w99flnqFTM6AtPNv1DvbCLx8zUV+MlnluqLUsRDmcTarwnq6K0+TLgYZWv21dkZ4wZrLCFy/Ndvb6516aKVECyD+G+RIk2hgG2AoxdGFYHFFygcPSCdBeZ1RCS9bbBMZjhg2PnFtsezxsa+lvo5d+OZMzw7ZZNjYsS1RQJgaMg55jSBwzBopSMUgqW4buhn5BEEy2oRRaMDqL2LDTsIbsvQTGVY5r6yaxhW+MXLtjyWWtG0GILOJMarK7MbVy2XoEzW+gyokkIf+Zt9uet9YQzmTqu83Q55vmDIVn5Jz11q8VhIoF3uh+AAME6HNCYmD8++kcSOc3XH900hmP4xNklpIFW9T5DSlrc3V/f4HXSf+fIC/sU5iP046WPIlFSv9gkR17QgUzUf1WsxFdcATrT9hvK5RJb48XdD00no="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
