travis:
  secure:
    BINSTAR_TOKEN: YO7S3IQkf+m4NFg6cj+oX9wljXqrDbdtvvYvfha69nuSxKVZrN4GRkq1+rDx0VVun0iO0jaO85bOfnCAMt2ZYOZx+A753uTUfy6XpA7jnIOozk3d2hIiALN40unxfxuV/DUJSgJtPqe4z+UHhfBo+JzqpmAnK3w7i2B4qPAd3BNgN2oEDOCi+dwMqHey1rOEqW/nhG1hz0PBUWGqhoG/J0YAMO9KGWIS3ocTzFddPH8NeEYqQ4+37jM8SM8q1FH0h3M5w99flnqFTM6AtPNv1DvbCLx8zUV+MlnluqLUsRDmcTarwnq6K0+TLgYZWv21dkZ4wZrLCFy/Ndvb6516aKVECyD+G+RIk2hgG2AoxdGFYHFFygcPSCdBeZ1RCS9bbBMZjhg2PnFtsezxsa+lvo5d+OZMzw7ZZNjYsS1RQJgaMg55jSBwzBopSMUgqW4buhn5BEEy2oRRaMDqL2LDTsIbsvQTGVY5r6yaxhW+MXLtjyWWtG0GILOJMarK7MbVy2XoEzW+gyokkIf+Zt9uet9YQzmTqu83Q55vmDIVn5Jz11q8VhIoF3uh+AAME6HNCYmD8++kcSOc3XH900hmP4xNklpIFW9T5DSlrc3V/f4HXSf+fIC/sU5iP046WPIlFSv9gkR17QgUzUf1WsxFdcATrT9hvK5RJb48XdD00no=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
