appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HPFr6gtpInTDIV3w7XIiGuJYq6ropevRGDEdjKHUZEL5KnW3ah7pZnNNlki1uUqhPBUBAo2YzPgtROtXIu4s0su4kwiY59P5YiveDjhoX2up2Ac0/0uZ4hee/aE76akbqhog91MoQeytnVHYL8YcunkcCv1rMQcebqMXLaWwUrdPKl1p1++o1/ltxbgfeMNlAyh8bIO9cU3Wqs6eNY9RgGG9vEvCyUGpa6b8P2q/grujDUkA5ER8fGyLXJdtBYHIY6EI93U3WPJ0KXWgivgAu3gg4H/lc+DBFsq1mewbnUjhOr5nScq5ebrD8YCSpfByxngOy9fd7wTvsQOA5WbYQ7aHogVxlW7psGGUoQdFHEMF2lzWLDbchdHPa5TNBCHeV/ilnXWyOneMrRXPXeunzYojzy+eKGZe9iRIM4OuXKiMWCHnsuus1Gr/k0Gh6Xdjn9zH3DlNwybnuWrhvl9xXSD1dxvoX+hAtzWCs9PucE+OD/wvuxZzAwsX6YPGLboeCZ3Bcq9azlUsuKrMgXWyDxRqQBhxbZpVUBuP+S0PNQvihuaFILHH1kItcG1pWRnNq+4doqFbL9y9LZuwDxnJIhsQ019KJ0xfQlTF3X1wDZl1KdNNUId6ScisJchWDjsNUu5PdVqKBwQvuTwI8DBuP73OxPcPi0exjblfD8Vlul0=}
conda_forge_output_validation: true
